---
title: "C01 Games EDA"
author: "Connor Quin"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
# Libraries
library(tidyverse)

# Parameters
rds_path <- here::here("data/games.rds")
#===============================================================================

# Code
```


Here is the first draft of my initial C01 analysis on lichess's database chess data. As a first run, I'm using data from Lichess's January 2013 database. The raw PGN file is 16.1 MB, with 121,332 games.

To start, let's read in this data

```{r}
games <-
  read_rds(rds_path)

glimpse(games)
summary(games)
```




```{r}
# Some initial plots:

# Distribution of white ratings
games %>% 
  ggplot(mapping = aes(x = white_elo)) +
  geom_histogram(binwidth = 10) +
  geom_vline(aes(xintercept = median(games$white_elo), color = "Median"))

# Distribution of changes to white ratings
games %>% 
  ggplot(mapping = aes(x = white_elo_diff)) +
  geom_histogram(binwidth = 10) +
  geom_vline(aes(xintercept = median(games$white_elo_diff), color = "Median"))
```


```{r}
# Initial plots: how do opening codes look?

# Among all games
games %>%
  transmute(
    eco_start = substring(eco, 1, 1),
    above_1700 = white_elo >= 1700 & black_elo >= 1700) %>%
  count(eco_start, above_1700) %>%
  group_by(above_1700) %>% 
  mutate(
    prop = n / sum(n)
  ) %>% 
  ggplot(mapping = aes(x = eco_start, y = prop)) +
  geom_col(mapping = aes(fill = above_1700)) +
  facet_grid(cols = vars(above_1700))


```









